# Generated by Django 2.2.7 on 2019-11-23 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('read', models.BooleanField(default=False)),
                ('transaction_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.TransactionLog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
